package jForms;


import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lutfijamaluddin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        viewPropertyButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        managerMenu = new javax.swing.JMenu();
        managerRegisterMenu = new javax.swing.JMenuItem();
        managerLoginMenu = new javax.swing.JMenuItem();
        clerkMenu = new javax.swing.JMenu();
        clerkRegisterMenu = new javax.swing.JMenuItem();
        clerkLoginMenu = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        viewPropertyButton.setText("View Property");
        viewPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPropertyButtonActionPerformed(evt);
            }
        });

        menuBar.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        menuBar.add(exitMenu);

        jMenuBar1.add(menuBar);

        managerMenu.setText("Manager");

        managerRegisterMenu.setText("Register");
        managerRegisterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerRegisterMenuActionPerformed(evt);
            }
        });
        managerMenu.add(managerRegisterMenu);

        managerLoginMenu.setText("Login");
        managerLoginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLoginMenuActionPerformed(evt);
            }
        });
        managerMenu.add(managerLoginMenu);

        jMenuBar1.add(managerMenu);

        clerkMenu.setText("Clerk");

        clerkRegisterMenu.setText("Register");
        clerkRegisterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkRegisterMenuActionPerformed(evt);
            }
        });
        clerkMenu.add(clerkRegisterMenu);

        clerkLoginMenu.setText("Login");
        clerkLoginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkLoginMenuActionPerformed(evt);
            }
        });
        clerkMenu.add(clerkLoginMenu);

        jMenuBar1.add(clerkMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(viewPropertyButton)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(viewPropertyButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void managerLoginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLoginMenuActionPerformed
        new ManagerLogin().setVisible(true);
        dispose(); // Closes window
    }//GEN-LAST:event_managerLoginMenuActionPerformed

    private void viewPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPropertyButtonActionPerformed
        try {
            new PropertyMainMenu().setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewPropertyButtonActionPerformed

    private void clerkLoginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkLoginMenuActionPerformed
        new BookingAgentLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_clerkLoginMenuActionPerformed

    private void managerRegisterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerRegisterMenuActionPerformed
       new AddManager().setVisible(true);
       dispose();
    }//GEN-LAST:event_managerRegisterMenuActionPerformed

    private void clerkRegisterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkRegisterMenuActionPerformed
        new AddClerk().setVisible(true);
        dispose();
    }//GEN-LAST:event_clerkRegisterMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clerkLoginMenu;
    private javax.swing.JMenu clerkMenu;
    private javax.swing.JMenuItem clerkRegisterMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem managerLoginMenu;
    private javax.swing.JMenu managerMenu;
    private javax.swing.JMenuItem managerRegisterMenu;
    private javax.swing.JMenu menuBar;
    private javax.swing.JButton viewPropertyButton;
    // End of variables declaration//GEN-END:variables
}
