package jForms;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/


import static jForms.PropertyMenu.counter;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author lutfijamaluddin
 */
public final class RecommendedProperty extends javax.swing.JFrame {    
    /**
     * Creates new form PropertyMenu
     * @throws java.io.IOException
     */
    public RecommendedProperty() throws IOException {
        initComponents();
        initProperty();
    }
    
    public void initProperty() throws IOException {
        try {
            Statement s = DriverManager.getConnection("jdbc:derby://localhost:1527/OOP", "ludwig", "password").createStatement();
//            String sql = "SELECT * FROM Property WHERE ID = " + counter + "AND STATE = " + "'" + PropertyMainMenu.state + "'";
String sql = "SELECT * FROM Property WHERE STATE = " + "'" + PropertyMainMenu.state + "'"  + "AND ID = " + counter;
ResultSet rs = s.executeQuery(sql);

while(rs.next()) {
    propertyName.setText(rs.getString("NAME"));
    propertyType.setText(rs.getString("TYPE"));
    
    forRent.setSelected(rs.getBoolean("TORENT"));
    forSale.setSelected(rs.getBoolean("TOSELL"));
    
    propertyState.setText(rs.getString("STATE"));
    propertyArea.setText(rs.getString("ADDRESS"));
    propertyPrice.setText(rs.getString("PRICE"));
    propertySize.setText(rs.getString("SQUAREFOOTAGE"));
    
    InputStream propertyImageIS = rs.getBinaryStream("IMAGE");
    // Decode the inputstream as BufferedImage
    BufferedImage propertyImageBuff;
    propertyImageBuff = ImageIO.read(propertyImageIS);
    Image propertyImageI = propertyImageBuff;
    ImageIcon propertyImageIcon =new ImageIcon(propertyImageI);
    propertyImage.setIcon(propertyImageIcon);
    
    InputStream propertyMapIS = rs.getBinaryStream("MAP");
    // Decode the inputstream as BufferedImage
    BufferedImage propertyMapBuff;
    propertyMapBuff = ImageIO.read(propertyMapIS);
    Image propertyMapI = propertyMapBuff;
    ImageIcon propertyMapIcon =new ImageIcon(propertyMapI);
    propertyMap.setIcon(propertyMapIcon);
}

        } catch (SQLException ex) {
            Logger.getLogger(RecommendedProperty.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int getTableSize() {
        int size = 0;
        try {
            Statement s = DriverManager.getConnection("jdbc:derby://localhost:1527/OOP", "ludwig", "password").createStatement();
            String sql = "SELECT count(*) FROM Property";
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()) {
                size = rs.getInt(1);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RecommendedProperty.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return size;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        propertyType = new javax.swing.JLabel();
        forRent = new javax.swing.JCheckBox();
        forSale = new javax.swing.JCheckBox();
        propertyState = new javax.swing.JLabel();
        propertyArea = new javax.swing.JLabel();
        propertyPrice = new javax.swing.JLabel();
        propertySize = new javax.swing.JLabel();
        contactManagerButton = new javax.swing.JButton();
        propertyType1 = new javax.swing.JLabel();
        propertyType2 = new javax.swing.JLabel();
        propertyImage = new javax.swing.JLabel();
        propertyMap = new javax.swing.JLabel();
        propertyName = new javax.swing.JLabel();
        closeFormButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        mainMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Properties");

        propertyType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyType.setText("<TYPE>");
        propertyType.setToolTipText("");

        forRent.setEnabled(false);
        forRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forRentActionPerformed(evt);
            }
        });

        forSale.setEnabled(false);
        forSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forSaleActionPerformed(evt);
            }
        });

        propertyState.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyState.setText("<STATE>");
        propertyState.setToolTipText("");

        propertyArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyArea.setText("<AREA>");
        propertyArea.setToolTipText("");

        propertyPrice.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyPrice.setText("<PRICE>");
        propertyPrice.setToolTipText("");

        propertySize.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertySize.setText("<SIZE RANGE SQFT>");
        propertySize.setToolTipText("");

        contactManagerButton.setText("Contact Manager");
        contactManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactManagerButtonActionPerformed(evt);
            }
        });

        propertyType1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyType1.setText("For Rent");
        propertyType1.setToolTipText("");

        propertyType2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        propertyType2.setText("For Sale");
        propertyType2.setToolTipText("");

        propertyImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        propertyMap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        propertyName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        propertyName.setText("<NAME>");
        propertyName.setToolTipText("");

        closeFormButton.setText("Close");
        closeFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(propertyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propertyMap, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contactManagerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeFormButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(propertySize, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propertyState, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propertyArea, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(propertyType1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertyType2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(forSale)
                                .addComponent(forRent)))
                        .addComponent(propertyName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(propertyMap, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeFormButton)
                    .addComponent(contactManagerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(propertyName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(propertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(propertyType2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(forRent)
                                    .addGap(18, 18, 18)))
                            .addComponent(propertyType1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(forSale)
                            .addGap(46, 46, 46)
                            .addComponent(propertyState, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(propertyArea, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(propertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(propertySize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(258, Short.MAX_VALUE)))
        );

        menuBar.setText("File");

        mainMenu.setText("Main Menu");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });
        menuBar.add(mainMenu);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        menuBar.add(exitMenu);

        jMenuBar1.add(menuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMenuActionPerformed
    
    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed
    
    private void closeFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeFormButtonActionPerformed
    
    private void contactManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactManagerButtonActionPerformed
        new ContactManager().setVisible(true);
    }//GEN-LAST:event_contactManagerButtonActionPerformed
    
    private void forSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forSaleActionPerformed
    
    private void forRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forRentActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecommendedProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecommendedProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecommendedProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecommendedProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new RecommendedProperty().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RecommendedProperty.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeFormButton;
    private javax.swing.JButton contactManagerButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JCheckBox forRent;
    private javax.swing.JCheckBox forSale;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mainMenu;
    private javax.swing.JMenu menuBar;
    private javax.swing.JLabel propertyArea;
    private javax.swing.JLabel propertyImage;
    private javax.swing.JLabel propertyMap;
    private javax.swing.JLabel propertyName;
    private javax.swing.JLabel propertyPrice;
    private javax.swing.JLabel propertySize;
    private javax.swing.JLabel propertyState;
    private javax.swing.JLabel propertyType;
    private javax.swing.JLabel propertyType1;
    private javax.swing.JLabel propertyType2;
    // End of variables declaration//GEN-END:variables
}
